### ISSUE TITLE
Errores en getData dejan el archivo GDS abierto

### ISSUE THREAD

**Issue by yocra3** [isglobal-brge/recombClust#1]
Te listo los errores en getData que dejan el archivo GDS abierto:

Falta de variantes en la región
```
> snpsData <- getData(gds, range, samples, 0.1)
# of selected variants: 0
# of selected samples: 503
Error in seqParallel(parallel, gdsfile, split = "by.variant", .combine = "list",  : 
  No variants selected.
```

Nombres de muestras duplicadas:
```
> snpsData <- getData(gds, range, samples, 0.1)
# of selected variants: 1,101,674
# of selected samples: 503
[==================================================] 100%, completed, 10s
# of selected variants: 79,332
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
```

**Comment by dpelegri** [comment]
He solucionado distintos errores que dejaban el GDS abierto. 
Si en algún momento se queda el fichero bloqueado por un error de `recombClust`, puedes utilizar la instrucción : 
`showfile.gds(closeall=TRUE)`
de la librería : `gdsfmt`. Esta instrucción cierra todos los gds abiertos
Prueba a ver si te funciona bien
